name: Destroy Infra
on:
  workflow_dispatch:
      
jobs:

  DestroyAWSInfra:
    name: AWS Infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Application
        uses: actions/checkout@v3
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.5
          
      - name: Terraform Init
        id: init
        run: |
          cd terraform/
          terraform init
        continue-on-error: false
      
      - name: Terraform Destroy
        id: destroy
        run: |
          cd terraform/
          terraform destroy -auto-approve
        continue-on-error: false
