name: Destroy infrastructure
on:
  workflow_dispatch:
jobs:
  DestroyAWSinfra:
      runs-on: ubuntu-latest
      steps:
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
            aws-region: us-east-1
        
        - name: Checkout Application
          uses: actions/checkout@v3
  
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: 0.13.5
  
        - name: Terraform Init and Plan
          run: |
            id:init
            cd terraform/
            terraform init
          continue-on-error: false
  
        - name: Terraform Destroy
          run: |
            id: destroy
            cd terraform/
            terraform destroy -auto-approve
