name: Deploy Docker and Ec2
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  BuildContainer:
    name: Build Container
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: pablofischer
      IMAGE_NAME: app-node
      IMAGE_TAG: 2.0
    steps:
      - name: Checkout Application
        uses: actions/checkout@v3
    
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: pablofischer/app-node:2.0
          
  CreateInfra:
    name: Create AWS Infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Application
        uses: actions/checkout@v3
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.5
          
      - name: Terraform Fmt
        id: fmt
        run: |
          cd terraform/
          terraform fmt
        continue-on-error: false

      - name: Terraform Init
        id: init
        run: |
          cd terraform/
          terraform init
        continue-on-error: false
      
      - name: Terraform Plan
        id: plan
        run: |
          cd terraform/
          terraform plan
        continue-on-error: false

      - name: Terraform Apply
        id: apply
        run: |
          cd terraform/
          terraform apply -auto-approve
        continue-on-error: false
