name: Deploy Docker and Ec2
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  BuildContainer:
    name: Build Container
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO: pablofischer
      IMAGE_NAME: app-node
      IMAGE_TAG: 2.0
    steps:
      - name: Checkout Application
        uses: actions/checkout@v3
    
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build And Push Docker Image
        run: |
          docker build -t ${DOCKER_REPO}/${IMAGE_NAME}:${IMAGE_TAG} .
          docker image push ${DOCKER_REPO}/${IMAGE_NAME}:${IMAGE_TAG}
